In [4]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import warnings
import random
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [5]:
X=pd.read_csv("X_train_pp2.csv",header=None)
Y=pd.read_csv("y_train2.csv",header=None)
X_val=pd.read_csv("X_val_pp2.csv",header=None)
Y_val=pd.read_csv("y_val2.csv",header=None)

In [5]:
# X_train=pd.concat([X_train_0,X_train_1], axis = 0)

In [6]:
# Y_train=X_train['click']

In [7]:
# del X_train['click']

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import f1_score, recall_score, precision_score, precision_recall_curve
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

In [5]:
X_train=X
Y_train=Y

In [6]:
# logisticRegr = LogisticRegression()
model = LogisticRegression(class_weight='balanced', C = 0.001)
model.fit(X_train, Y_train)


/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.001, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='warn', tol=0.0001, verbose=0, warm_start=False)

In [7]:
pred=model.predict_proba(X_val)[:, 1]

In [8]:
pred

array([0.23547684, 0.16053234, 0.11442798, ..., 0.3944132 , 0.13749598,
       0.31635371])

In [11]:
pred_click=model.predict(X_val)

In [12]:
pred_click

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
# predictions_prob.max()

In [28]:
# pred=predictions_prob

In [29]:
# thres=10**(-6)
# pred [pred > thres] = 1
# pred [pred <= thres] = 0

In [30]:
# pred

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_val,pred_click))
print(confusion_matrix(Y_val, pred_click))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90    303723
           1       0.00      0.68      0.01       202

   micro avg       0.82      0.82      0.82    303925
   macro avg       0.50      0.75      0.45    303925
weighted avg       1.00      0.82      0.90    303925

[[250379  53344]
 [    64    138]]


In [8]:
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, f1_score, precision_recall_curve


roc_auc_score(Y_val, prob)

0.8404377011322491

In [6]:
import pandas as pd

preddd=pd.read_csv('pred_lr.csv')

In [8]:
preddd=preddd['pre_click']


In [11]:
Y['click']=Y

In [12]:
Y

0  click
0        0      0
1        0      0
2        0      0
3        0      0
4        0      0
5        0      0
6        0      0
7        0      0
8        0      0
9        0      0
10       0      0
11       0      0
12       0      0
13       0      0
14       0      0
15       0      0
16       0      0
17       0      0
18       0      0
19       0      0
20       0      0
21       0      0
22       0      0
23       0      0
24       0      0
25       0      0
26       0      0
27       0      0
28       0      0
29       0      0
...     ..    ...
2430951  0      0
2430952  0      0
2430953  0      0
2430954  0      0
2430955  0      0
2430956  0      0
2430957  0      0
2430958  0      0
2430959  0      0
2430960  0      0
2430961  0      0
2430962  0      0
2430963  0      0
2430964  0      0
2430965  0      0
2430966  0      0
2430967  0      0
2430968  0      0
2430969  0      0
2430970  0      0
2430971  0      0
2430972  0      0
2430973  0      0
2430974  0      0
2430975  0      0
2430976  0      0
2430977  0      0
2430978  0      0
2430979  0      0
2430980  0      0

[2430981 rows x 2 columns]

In [23]:
Y['click']=Y

In [29]:
# re calibrated predictions
# q = p / (p + (1-p) / w

pred =[]
# pred_test=[]

a = np.bincount(Y.click)
w = a[1] / a[0]

for p in preddd:
    pred.append( p / (p + ((1-p)/w)))

# for p in pCTR_test[1]:
#     pred_test.append( p / (p + ((1-p)/w)))

In [30]:
pred

[0.00022728877253116187,
 0.00014112905639319468,
 9.536435680643275e-05,
 7.94306576848656e-05,
 9.763929171715522e-05,
 0.00044050457169704754,
 0.00042551524063379805,
 0.0005796655727086007,
 0.0001332964821986005,
 0.00012669880456027223,
 0.00039673901135850985,
 0.0001484877031604182,
 0.00019001291841461864,
 0.00025844667292981567,
 0.0007817453015785988,
 0.00023486711661329165,
 0.00016294432389758263,
 0.00014663671716144927,
 0.0010192644634892342,
 0.00010489990208657562,
 0.0004788415089226661,
 0.0003981108324056129,
 0.0002530967339357867,
 0.00026471151864466795,
 0.002171409512508471,
 0.0006871674967928994,
 3.442341953451179e-05,
 0.00046477094175498875,
 3.203735451807189e-05,
 0.00022941929098851979,
 0.00028236699100924796,
 0.00047470591607510885,
 0.00023743298278088476,
 0.0006552045669797493,
 0.0003047037023794253,
 7.282276364299868e-05,
 0.00034767329511004193,
 0.00015628773671036902,
 0.0003003799875742346,
 0.00015521535690320808,
 0.000755930799410547

In [14]:
pred

[0.00022728877253116187,
 0.00014112905639319468,
 9.536435680643275e-05,
 7.94306576848656e-05,
 9.763929171715522e-05,
 0.00044050457169704754,
 0.00042551524063379805,
 0.0005796655727086007,
 0.0001332964821986005,
 0.00012669880456027223,
 0.00039673901135850985,
 0.0001484877031604182,
 0.00019001291841461864,
 0.00025844667292981567,
 0.0007817453015785988,
 0.00023486711661329165,
 0.00016294432389758263,
 0.00014663671716144927,
 0.0010192644634892342,
 0.00010489990208657562,
 0.0004788415089226661,
 0.0003981108324056129,
 0.0002530967339357867,
 0.00026471151864466795,
 0.002171409512508471,
 0.0006871674967928994,
 3.442341953451179e-05,
 0.00046477094175498875,
 3.203735451807189e-05,
 0.00022941929098851979,
 0.00028236699100924796,
 0.00047470591607510885,
 0.00023743298278088476,
 0.0006552045669797493,
 0.0003047037023794253,
 7.282276364299868e-05,
 0.00034767329511004193,
 0.00015628773671036902,
 0.0003003799875742346,
 0.00015521535690320808,
 0.000755930799410547

In [16]:
del Y['click']

In [14]:
pred=pd.DataFrame(columns=['pre_click'],data=pred)#数据有三列，列名分别为one,two,three
pred.to_csv('pred_lr.csv')

In [19]:
pred_final=pd.DataFrame(columns=['pre_click_final'],data=pred)#数据有三列，列名分别为one,two,three
pred_final.to_csv('pred_lr_final.csv')